import Head from 'next/head'
import Image from 'next/image'
import MainLayout from '../components/layouts/mainLayout'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Basic Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>

    <MainLayout>

        <h1 className={styles.title}>
          Welcome to Basic Frontend    </h1>
    </MainLayout>

        
    </div>
  )
}
